[build]
builder = "Nixpacks"

[nixpacks]
environments = ["php", "nodejs"]

[phases.setup]
nixPkgs = ["php81", "php81Extensions.curl", "php81Extensions.mbstring", "php81Extensions.tokenizer", "php81Extensions.xml", "php81Extensions.pdo_mysql", "composer"]

[phases.install]
cmds = [
  "cd laravel_backend",
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "cd laravel_backend",
  "php artisan key:generate"
]

[start]
cmd = "cd laravel_backend && php artisan serve --host=0.0.0.0 --port=$PORT"
