[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "php81",
  "php81Extensions.curl",
  "php81Extensions.mbstring",
  "php81Extensions.tokenizer",
  "php81Extensions.xml",
  "php81Extensions.pdo_mysql",
  "php81Extensions.zip",
  "composer"
],
cmds = [
  "cd laravel_backend",
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate",
  "php artisan migrate"
]

[phases.install]
cmds = [
  "cd laravel_backend",
  "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-grpc"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
